package main

// Country codes used by passportindex.org (ISO 3166-1 alpha-2 lowercase).
var countryCodes = []string{
	"af", "al", "dz", "ad", "ao", "ag", "ar", "am", "au", "at",
	"az", "bs", "bh", "bd", "bb", "by", "be", "bz", "bj", "bt",
	"bo", "ba", "bw", "br", "bn", "bg", "bf", "bi", "kh", "cm",
	"ca", "cv", "cf", "td", "cl", "cn", "co", "km", "cg", "cd",
	"cr", "ci", "hr", "cu", "cy", "cz", "dk", "dj", "dm", "do",
	"ec", "eg", "sv", "gq", "er", "ee", "sz", "et", "fj", "fi",
	"fr", "ga", "gm", "ge", "de", "gh", "gr", "gd", "gt", "gn",
	"gw", "gy", "ht", "hn", "hu", "is", "in", "id", "ir", "iq",
	"ie", "il", "it", "jm", "jp", "jo", "kz", "ke", "ki", "kp",
	"kr", "kw", "kg", "la", "lv", "lb", "ls", "lr", "ly", "li",
	"lt", "lu", "mg", "mw", "my", "mv", "ml", "mt", "mh", "mr",
	"mu", "mx", "fm", "md", "mc", "mn", "me", "ma", "mz", "mm",
	"na", "nr", "np", "nl", "nz", "ni", "ne", "ng", "mk", "no",
	"om", "pk", "pw", "ps", "pa", "pg", "py", "pe", "ph", "pl",
	"pt", "qa", "ro", "ru", "rw", "kn", "lc", "vc", "ws", "sm",
	"st", "sa", "sn", "rs", "sc", "sl", "sg", "sk", "si", "sb",
	"so", "za", "ss", "es", "lk", "sd", "sr", "se", "ch", "sy",
	"tw", "tj", "tz", "th", "tl", "tg", "to", "tt", "tn", "tr",
	"tm", "tv", "ug", "ua", "ae", "gb", "us", "uy", "uz", "vu",
	"va", "ve", "vn", "xk", "ye", "zm", "zw",
	// Special territories:
	"hk", "mo",
}

var iso2ToName = map[string]string{
	"af": "Afghanistan",
	"al": "Albania",
	"dz": "Algeria",
	"ad": "Andorra",
	"ao": "Angola",
	"ag": "Antigua and Barbuda",
	"ar": "Argentina",
	"am": "Armenia",
	"au": "Australia",
	"at": "Austria",
	"az": "Azerbaijan",
	"bs": "Bahamas",
	"bh": "Bahrain",
	"bd": "Bangladesh",
	"bb": "Barbados",
	"by": "Belarus",
	"be": "Belgium",
	"bz": "Belize",
	"bj": "Benin",
	"bt": "Bhutan",
	"bo": "Bolivia",
	"ba": "Bosnia and Herzegovina",
	"bw": "Botswana",
	"br": "Brazil",
	"bn": "Brunei",
	"bg": "Bulgaria",
	"bf": "Burkina Faso",
	"bi": "Burundi",
	"kh": "Cambodia",
	"cm": "Cameroon",
	"ca": "Canada",
	"cv": "Cape Verde",
	"cf": "Central African Republic",
	"td": "Chad",
	"cl": "Chile",
	"cn": "China",
	"co": "Colombia",
	"km": "Comoros",
	"cg": "Congo",
	"cd": "DR Congo",
	"cr": "Costa Rica",
	"ci": "Ivory Coast",
	"hr": "Croatia",
	"cu": "Cuba",
	"cy": "Cyprus",
	"cz": "Czech Republic",
	"dk": "Denmark",
	"dj": "Djibouti",
	"dm": "Dominica",
	"do": "Dominican Republic",
	"ec": "Ecuador",
	"eg": "Egypt",
	"sv": "El Salvador",
	"gq": "Equatorial Guinea",
	"er": "Eritrea",
	"ee": "Estonia",
	"sz": "Swaziland",
	"et": "Ethiopia",
	"fj": "Fiji",
	"fi": "Finland",
	"fr": "France",
	"ga": "Gabon",
	"gm": "Gambia",
	"ge": "Georgia",
	"de": "Germany",
	"gh": "Ghana",
	"gr": "Greece",
	"gd": "Grenada",
	"gt": "Guatemala",
	"gn": "Guinea",
	"gw": "Guinea-Bissau",
	"gy": "Guyana",
	"ht": "Haiti",
	"hn": "Honduras",
	"hk": "Hong Kong",
	"hu": "Hungary",
	"is": "Iceland",
	"in": "India",
	"id": "Indonesia",
	"ir": "Iran",
	"iq": "Iraq",
	"ie": "Ireland",
	"il": "Israel",
	"it": "Italy",
	"jm": "Jamaica",
	"jp": "Japan",
	"jo": "Jordan",
	"kz": "Kazakhstan",
	"ke": "Kenya",
	"ki": "Kiribati",
	"xk": "Kosovo",
	"kw": "Kuwait",
	"kg": "Kyrgyzstan",
	"la": "Laos",
	"lv": "Latvia",
	"lb": "Lebanon",
	"ls": "Lesotho",
	"lr": "Liberia",
	"ly": "Libya",
	"li": "Liechtenstein",
	"lt": "Lithuania",
	"lu": "Luxembourg",
	"mo": "Macao",
	"mg": "Madagascar",
	"mw": "Malawi",
	"my": "Malaysia",
	"mv": "Maldives",
	"ml": "Mali",
	"mt": "Malta",
	"mh": "Marshall Islands",
	"mr": "Mauritania",
	"mu": "Mauritius",
	"mx": "Mexico",
	"fm": "Micronesia",
	"md": "Moldova",
	"mc": "Monaco",
	"mn": "Mongolia",
	"me": "Montenegro",
	"ma": "Morocco",
	"mz": "Mozambique",
	"mm": "Myanmar",
	"na": "Namibia",
	"nr": "Nauru",
	"np": "Nepal",
	"nl": "Netherlands",
	"nz": "New Zealand",
	"ni": "Nicaragua",
	"ne": "Niger",
	"ng": "Nigeria",
	"kp": "North Korea",
	"mk": "North Macedonia",
	"no": "Norway",
	"om": "Oman",
	"pk": "Pakistan",
	"pw": "Palau",
	"ps": "Palestine",
	"pa": "Panama",
	"pg": "Papua New Guinea",
	"py": "Paraguay",
	"pe": "Peru",
	"ph": "Philippines",
	"pl": "Poland",
	"pt": "Portugal",
	"qa": "Qatar",
	"ro": "Romania",
	"ru": "Russia",
	"rw": "Rwanda",
	"kn": "Saint Kitts and Nevis",
	"lc": "Saint Lucia",
	"vc": "Saint Vincent and the Grenadines",
	"ws": "Samoa",
	"sm": "San Marino",
	"st": "Sao Tome and Principe",
	"sa": "Saudi Arabia",
	"sn": "Senegal",
	"rs": "Serbia",
	"sc": "Seychelles",
	"sl": "Sierra Leone",
	"sg": "Singapore",
	"sk": "Slovakia",
	"si": "Slovenia",
	"sb": "Solomon Islands",
	"so": "Somalia",
	"za": "South Africa",
	"kr": "South Korea",
	"ss": "South Sudan",
	"es": "Spain",
	"lk": "Sri Lanka",
	"sd": "Sudan",
	"sr": "Suriname",
	"se": "Sweden",
	"ch": "Switzerland",
	"sy": "Syria",
	"tw": "Taiwan",
	"tj": "Tajikistan",
	"tz": "Tanzania",
	"th": "Thailand",
	"tl": "Timor-Leste",
	"tg": "Togo",
	"to": "Tonga",
	"tt": "Trinidad and Tobago",
	"tn": "Tunisia",
	"tr": "Turkey",
	"tm": "Turkmenistan",
	"tv": "Tuvalu",
	"ug": "Uganda",
	"ua": "Ukraine",
	"ae": "United Arab Emirates",
	"gb": "United Kingdom",
	"us": "United States",
	"uy": "Uruguay",
	"uz": "Uzbekistan",
	"vu": "Vanuatu",
	"va": "Vatican",
	"ve": "Venezuela",
	"vn": "Vietnam",
	"ye": "Yemen",
	"zm": "Zambia",
	"zw": "Zimbabwe",
}

var iso2ToISO3 = map[string]string{
	"af": "AFG",
	"al": "ALB",
	"dz": "DZA",
	"ad": "AND",
	"ao": "AGO",
	"ag": "ATG",
	"ar": "ARG",
	"am": "ARM",
	"au": "AUS",
	"at": "AUT",
	"az": "AZE",
	"bs": "BHS",
	"bh": "BHR",
	"bd": "BGD",
	"bb": "BRB",
	"by": "BLR",
	"be": "BEL",
	"bz": "BLZ",
	"bj": "BEN",
	"bt": "BTN",
	"bo": "BOL",
	"ba": "BIH",
	"bw": "BWA",
	"br": "BRA",
	"bn": "BRN",
	"bg": "BGR",
	"bf": "BFA",
	"bi": "BDI",
	"kh": "KHM",
	"cm": "CMR",
	"ca": "CAN",
	"cv": "CPV",
	"cf": "CAF",
	"td": "TCD",
	"cl": "CHL",
	"cn": "CHN",
	"co": "COL",
	"km": "COM",
	"cg": "COG",
	"cd": "COD",
	"cr": "CRI",
	"ci": "CIV",
	"hr": "HRV",
	"cu": "CUB",
	"cy": "CYP",
	"cz": "CZE",
	"dk": "DNK",
	"dj": "DJI",
	"dm": "DMA",
	"do": "DOM",
	"ec": "ECU",
	"eg": "EGY",
	"sv": "SLV",
	"gq": "GNQ",
	"er": "ERI",
	"ee": "EST",
	"sz": "SWZ",
	"et": "ETH",
	"fj": "FJI",
	"fi": "FIN",
	"fr": "FRA",
	"ga": "GAB",
	"gm": "GMB",
	"ge": "GEO",
	"de": "DEU",
	"gh": "GHA",
	"gr": "GRC",
	"gd": "GRD",
	"gt": "GTM",
	"gn": "GIN",
	"gw": "GNB",
	"gy": "GUY",
	"ht": "HTI",
	"hn": "HND",
	"hk": "HKG",
	"hu": "HUN",
	"is": "ISL",
	"in": "IND",
	"id": "IDN",
	"ir": "IRN",
	"iq": "IRQ",
	"ie": "IRL",
	"il": "ISR",
	"it": "ITA",
	"jm": "JAM",
	"jp": "JPN",
	"jo": "JOR",
	"kz": "KAZ",
	"ke": "KEN",
	"ki": "KIR",
	"xk": "XKX",
	"kw": "KWT",
	"kg": "KGZ",
	"la": "LAO",
	"lv": "LVA",
	"lb": "LBN",
	"ls": "LSO",
	"lr": "LBR",
	"ly": "LBY",
	"li": "LIE",
	"lt": "LTU",
	"lu": "LUX",
	"mo": "MAC",
	"mg": "MDG",
	"mw": "MWI",
	"my": "MYS",
	"mv": "MDV",
	"ml": "MLI",
	"mt": "MLT",
	"mh": "MHL",
	"mr": "MRT",
	"mu": "MUS",
	"mx": "MEX",
	"fm": "FSM",
	"md": "MDA",
	"mc": "MCO",
	"mn": "MNG",
	"me": "MNE",
	"ma": "MAR",
	"mz": "MOZ",
	"mm": "MMR",
	"na": "NAM",
	"nr": "NRU",
	"np": "NPL",
	"nl": "NLD",
	"nz": "NZL",
	"ni": "NIC",
	"ne": "NER",
	"ng": "NGA",
	"kp": "PRK",
	"mk": "MKD",
	"no": "NOR",
	"om": "OMN",
	"pk": "PAK",
	"pw": "PLW",
	"ps": "PSE",
	"pa": "PAN",
	"pg": "PNG",
	"py": "PRY",
	"pe": "PER",
	"ph": "PHL",
	"pl": "POL",
	"pt": "PRT",
	"qa": "QAT",
	"ro": "ROU",
	"ru": "RUS",
	"rw": "RWA",
	"kn": "KNA",
	"lc": "LCA",
	"vc": "VCT",
	"ws": "WSM",
	"sm": "SMR",
	"st": "STP",
	"sa": "SAU",
	"sn": "SEN",
	"rs": "SRB",
	"sc": "SYC",
	"sl": "SLE",
	"sg": "SGP",
	"sk": "SVK",
	"si": "SVN",
	"sb": "SLB",
	"so": "SOM",
	"za": "ZAF",
	"kr": "KOR",
	"ss": "SSD",
	"es": "ESP",
	"lk": "LKA",
	"sd": "SDN",
	"sr": "SUR",
	"se": "SWE",
	"ch": "CHE",
	"sy": "SYR",
	"tw": "TWN",
	"tj": "TJK",
	"tz": "TZA",
	"th": "THA",
	"tl": "TLS",
	"tg": "TGO",
	"to": "TON",
	"tt": "TTO",
	"tn": "TUN",
	"tr": "TUR",
	"tm": "TKM",
	"tv": "TUV",
	"ug": "UGA",
	"ua": "UKR",
	"ae": "ARE",
	"gb": "GBR",
	"us": "USA",
	"uy": "URY",
	"uz": "UZB",
	"vu": "VUT",
	"va": "VAT",
	"ve": "VEN",
	"vn": "VNM",
	"ye": "YEM",
	"zm": "ZMB",
	"zw": "ZWE",
}

// Sort key overrides: some countries are displayed with one name but sorted by another.
// These overrides apply to both row and column ordering.
var sortKeyBase = map[string]string{
	"cd": "Congo, Democratic Republic of the", // displayed as "DR Congo"
	"ci": "Cote d'Ivoire",                     // displayed as "Ivory Coast"
	"sz": "Eswatini",                          // displayed as "Swaziland"
	"vc": "St Vincent and the Grenadines",     // displayed as "Saint Vincent and the Grenadines"
}

// Additional column-only override: Turkey sorts as "Türkiye" in columns but not rows.
var sortKeyCol = map[string]string{
	"tr": "Türkiye", // displayed as "Turkey"
}
